<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MQLKO6I" failures="1" tests="10" name="Test" time="0.205" errors="0" timestamp="2020-07-12T11:51:49 IST">
  <testcase classname="test.day2" name="credentials" time="0.026"/>
  <testcase classname="test.day1" name="day1Demo" time="0.027"/>
  <testcase classname="test.day2" name="credentials" time="0.011"/>
  <testcase classname="test.day1" name="day1Demo1" time="0.009"/>
  <testcase classname="test.day2" name="credentials" time="0.002"/>
  <testcase classname="test.day2" name="day2Demo" time="0.004"/>
  <testcase classname="test.day2" name="day2Demo1" time="0.003"/>
  <testcase classname="test.day3" name="day3Demo6" time="0.007"/>
  <testcase classname="test.day3" name="day3Demo" time="0.01">
    <failure type="java.lang.AssertionError" message="did not expect to find [true] but found [false]">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at test.day3.day3Demo(day3.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:844)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- day3Demo -->
  <testcase classname="test.day3" name="day3Demo5" time="0.003"/>
</testsuite> <!-- Test -->
